#ifndef _APP_CONFIG_H_
#define _APP_CONFIG_H_


#define VENC_WIDTH   800
#define VENC_HEIGHT  480

#define FRAMERATE    30

/* image formats to use: */
#define IMG_FMT_LCD 1
#define IMG_FMT_YUV  2
#define IMG_FMT IMG_FMT_LCD

#if IMG_FMT == IMG_FMT_LCD
#define VENC_PREPROC_FMT H264ENC_RGB565
#define DCMIPP_PIPE1_OUT_FMT DCMIPP_PIXEL_PACKER_FORMAT_RGB565_1
#endif

#if IMG_FMT == IMG_FMT_YUV
#define VENC_PREPROC_FMT H264ENC_YUV422_INTERLEAVED_YUYV
#define DCMIPP_PIPE1_OUT_FMT DCMIPP_PIXEL_PACKER_FORMAT_YUV422_1
#endif

#endif
